---
- name: win_reg_stat module demo
  hosts: all
  tasks:
    - name: check .NET version
      ansible.windows.win_reg_stat:
        path: 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full'
        name: "Version"
      register: reg_val

    - name: print .NET version
      ansible.builtin.debug:
        msg: "{{ reg_val }}"
